[config]
backend = "MaterialYou"

[templates.foot]
input_path = "/home/badmaster67/nixos-dotfiles/config/matugen/templates/foot.ini"
output_path = "/home/badmaster67/.cache/matugen/foot.ini"
post_hook = "pkill -USR1 foot"

[templates.waybar]
input_path = "/home/badmaster67/nixos-dotfiles/config/matugen/templates/waybar.css"
output_path = "/home/badmaster67/.cache/matugen/waybar.css"
post_hook = "bash /home/badmaster67/nixos-dotfiles/config/mango/rebar.sh"

[templates.tmux]
input_path = "/home/badmaster67/nixos-dotfiles/config/matugen/templates/tmux.conf"
output_path = "/home/badmaster67/.cache/matugen/tmux.conf"
post_hook = "tmux source-file /home/badmaster67/.config/tmux/tmux.conf 2>/dev/null || true"

[templates.nvim]
input_path = "/home/badmaster67/nixos-dotfiles/config/matugen/templates/matugen_colors.lua"
output_path = "/home/badmaster67/.cache/matugen/matugen_colors.lua"

[templates.btop]
input_path = "/home/badmaster67/nixos-dotfiles/config/matugen/templates/btop.theme"
output_path = "/home/badmaster67/.cache/matugen/btop.theme"
post_hook = "pkill -USR2 btop || true"
